# Generated by Django 4.0.1 on 2024-03-23 04:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Addscholarships',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ScholarShip_Name', models.CharField(max_length=100)),
                ('Scholarship_Number', models.IntegerField()),
                ('Eligibility', models.CharField(max_length=100)),
                ('Start_Date', models.DateField()),
                ('End_Date', models.DateField()),
                ('Renewal_Date', models.DateField()),
                ('SchType', models.CharField(max_length=100)),
                ('Amount', models.IntegerField()),
                ('Scholarship_Period', models.CharField(max_length=100)),
                ('More', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='ForgotPassword',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('New_Password', models.CharField(max_length=100)),
                ('Confirm_Newpassword', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Login',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Username', models.CharField(max_length=100)),
                ('Password', models.CharField(max_length=100)),
                ('Type', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='Public_enquiry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=100)),
                ('Email', models.CharField(max_length=100)),
                ('Phoneno', models.BigIntegerField()),
                ('Enquiry', models.CharField(max_length=100)),
                ('Date', models.DateField()),
                ('Reply', models.CharField(max_length=100)),
                ('Reply_date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Sponsor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=100)),
                ('Address', models.CharField(max_length=100)),
                ('Place', models.CharField(max_length=100)),
                ('Pincode', models.IntegerField()),
                ('District', models.CharField(max_length=100)),
                ('Gender', models.CharField(max_length=100)),
                ('State', models.CharField(max_length=100)),
                ('Country', models.CharField(max_length=100)),
                ('Email', models.CharField(max_length=100)),
                ('Phoneno', models.BigIntegerField()),
                ('Proof', models.CharField(default=0, max_length=300)),
                ('Image', models.CharField(default=0, max_length=300)),
                ('LOGIN', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Scholarchain.login')),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(default='', max_length=100)),
                ('Dob', models.DateField()),
                ('Address', models.CharField(max_length=100)),
                ('Place', models.CharField(max_length=100)),
                ('Pincode', models.IntegerField()),
                ('District', models.CharField(max_length=100)),
                ('Gender', models.CharField(max_length=100)),
                ('State', models.CharField(max_length=100)),
                ('Country', models.CharField(max_length=100)),
                ('Email', models.CharField(max_length=100)),
                ('Phoneno', models.BigIntegerField()),
                ('Image', models.CharField(default=0, max_length=300)),
                ('Parent_Name', models.CharField(max_length=100)),
                ('Latest_Qualification', models.CharField(max_length=100)),
                ('Institution', models.CharField(max_length=100)),
                ('LOGIN', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Scholarchain.login')),
            ],
        ),
        migrations.CreateModel(
            name='Student_info',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Religion', models.CharField(max_length=100)),
                ('Caste', models.CharField(max_length=100)),
                ('Category', models.CharField(max_length=100)),
                ('Parent_Occupation', models.CharField(max_length=100)),
                ('Parent_Phoneno', models.BigIntegerField()),
                ('Income_Certificate', models.CharField(max_length=300)),
                ('Birth_Certificate', models.CharField(max_length=300)),
                ('Caste_Certificate', models.CharField(max_length=300)),
                ('Adhaar_Number', models.CharField(max_length=10)),
                ('Family_Income', models.CharField(max_length=10)),
                ('Bank_Accountno', models.CharField(max_length=10)),
                ('Ifsc_Code', models.CharField(max_length=100)),
                ('Branch_Name', models.CharField(max_length=100)),
                ('Holder_Name', models.CharField(max_length=100)),
                ('STUDENT', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Scholarchain.student')),
            ],
        ),
        migrations.CreateModel(
            name='Sponsor_interest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Date', models.DateField()),
                ('Time', models.TimeField()),
                ('Status', models.CharField(max_length=100)),
                ('ADDSCHOLARSHIPS', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Scholarchain.addscholarships')),
                ('SPONSOR', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Scholarchain.sponsor')),
            ],
        ),
        migrations.CreateModel(
            name='Portfolio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Type', models.CharField(max_length=100)),
                ('Institutions', models.CharField(max_length=100)),
                ('Percentage', models.BigIntegerField()),
                ('Cgpa', models.FloatField()),
                ('Certificates', models.CharField(max_length=300)),
                ('STUDENT', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Scholarchain.student')),
            ],
        ),
        migrations.CreateModel(
            name='Organizationpersonregistration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=100)),
                ('E_mail', models.CharField(max_length=100)),
                ('Phone', models.BigIntegerField()),
                ('Address', models.CharField(max_length=100)),
                ('Place', models.CharField(max_length=100)),
                ('District', models.CharField(max_length=100)),
                ('Pincode', models.IntegerField()),
                ('Proof', models.CharField(max_length=500)),
                ('Status', models.CharField(max_length=100)),
                ('LOGIN', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Scholarchain.login')),
            ],
        ),
        migrations.AddField(
            model_name='addscholarships',
            name='ORGANIZATION',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Scholarchain.organizationpersonregistration'),
        ),
    ]
