# Generated by Django 4.0.1 on 2024-03-23 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Scholarchain', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='portfolio',
            name='Cgpa',
        ),
        migrations.AlterField(
            model_name='portfolio',
            name='Percentage',
            field=models.CharField(max_length=50),
        ),
    ]
