# Generated by Django 4.0.1 on 2024-03-23 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Scholarchain', '0002_remove_portfolio_cgpa_alter_portfolio_percentage'),
    ]

    operations = [
        migrations.AddField(
            model_name='addscholarships',
            name='Score',
            field=models.CharField(default='', max_length=100),
        ),
    ]
