# Generated by Django 4.0.1 on 2024-03-23 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Scholarchain', '0003_addscholarships_score'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addscholarships',
            name='Score',
            field=models.IntegerField(),
        ),
    ]
