# Generated by Django 4.0.1 on 2024-04-05 08:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Scholarchain', '0006_student_required_sponsorship'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sponsor_Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Date', models.DateField()),
                ('SPONSOR', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Scholarchain.sponsor')),
                ('STUDENT', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Scholarchain.student')),
            ],
        ),
    ]
