# Generated by Django 4.0.1 on 2024-04-06 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Scholarchain', '0007_sponsor_student'),
    ]

    operations = [
        migrations.AddField(
            model_name='addscholarships',
            name='Status',
            field=models.CharField(default='Active', max_length=100),
        ),
    ]
