# Generated by Django 4.0.1 on 2024-04-13 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Scholarchain', '0009_public_enquiry_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='public_enquiry',
            name='Status',
            field=models.CharField(default=' pending', max_length=100),
        ),
    ]
